### ISSUE TITLE
Add ability to delete entries in transport discovery.

### ISSUE THREAD

**Issue by evanlinjin** [SkycoinProject/skywire-mainnet#10]
**Feature description**

Currently, one can only update statuses of entries in transport discovery and cannot actually delete entries.

This causes issues when restarting transports. When we remove transports from visor, we only remove them locally. On visor startup, it polls transport discovery to determine saved transports. Hence, locally deleted transports are revived.

**Implementation Details:**

- A transport between nodes A and B can only be deleted by A or B.

**Tasks:**

- [ ] Add endpoint to transport discovery to delete transport.
- [ ] Update transport discovery client.
- [ ] Update `(transport.Manager).DeleteTransport` to call transport discovery's delete transport endpoint.

**Comment by jdknives** [comment]
We should check, whether fixing this also fixes #30 .
